# Generated by Django 5.2.12 on 2026-03-05 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(max_length=80)),
                ('file_path', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=180)),
                ('file_type', models.CharField(blank=True, max_length=80)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stored_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
