# Generated by Django 5.2.12 on 2026-03-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('miss_count', models.PositiveIntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('last_miss_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cache_metrics',
                'ordering': ['-updated_at'],
            },
        ),
    ]
