# Generated by Django 5.2.12 on 2026-03-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='must_reset_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role_legacy_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
