# Generated by Django 5.2.12 on 2026-03-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=80)),
                ('merchant_id', models.CharField(max_length=120)),
                ('api_key_ref', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'integration_payments',
            },
        ),
    ]
