# Generated by Django 5.2.12 on 2026-03-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='id',
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
