# Generated by Django 5.2.12 on 2026-03-05 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='role',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_system',
        ),
        migrations.RemoveField(
            model_name='role',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='role',
            name='is_executive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(
                db_column='role_code',
                default='MEMBER',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_assignments',
                to='roles.role',
            ),
            preserve_default=False,
        ),
    ]
