# Generated by Django 5.2.12 on 2026-03-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_rename_user_roles_role_id_0b583b_idx_user_roles_role_co_49fe4a_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM pg_class
                            WHERE relkind = 'i'
                              AND relname = 'user_roles_role_id_0b583b_idx'
                        ) THEN
                            ALTER INDEX user_roles_role_id_0b583b_idx
                            RENAME TO user_roles_role_co_49fe4a_idx;
                        END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM pg_class
                            WHERE relkind = 'i'
                              AND relname = 'user_roles_role_co_49fe4a_idx'
                        ) THEN
                            ALTER INDEX user_roles_role_co_49fe4a_idx
                            RENAME TO user_roles_role_id_0b583b_idx;
                        END IF;
                    END $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='userrole',
                    old_name='user_roles_role_id_0b583b_idx',
                    new_name='user_roles_role_co_49fe4a_idx',
                ),
            ],
        ),
    ]
